/*
 * event_ids.h
 *
 *  Created on: 07.09.2013
 *      Author: valentin
 */

#ifndef EVENT_IDS_H_
#define EVENT_IDS_H_

#include <wx/wx.h>
#define NUMBEROFINTERPOLATIONMODES 2
const wxString imenumstrings[NUMBEROFINTERPOLATIONMODES] = {wxT("Linear"),wxT("Logarithmisch")};

/**
 * Konstante Event-IDs.
 */
enum EventID{
	ID_ABOUT = 1,
	ID_TEST,
	ID_IMPORT_OBJ,
	ID_IMPORT_SD,
	ID_RECALCBT,
	ID_MATERIALBOX,
	ID_ANALYZE,
	ID_GENERAL_PROP,
	ID_IMMEDIATE_UPDATE_PROP,
	ID_GENERAL_VIEW_PROP,
	ID_CHANGE_ACTIVE_OBJ,
	ID_ANALYZE_POINT,
	ID_ANALYZE_POINT_BT,
	ID_CUT_CANVAS,
	ID_RENDER_CUT,
	ID_RENDER_CUT_BT,
	ID_CUT_TRI_EDIT,
	ID_DELETE_ACTIVE_OBJ,
	ID_IMPORT_TSD,
	ID_SD_BOX,
	ID_SD_TIMELINE,
	ID_ANALYZE_MARKER_CB,
	ID_CLEAR_MARKER_BT,
	ID_MARKER_NEXT_BT,
	ID_MARKER_PREV_BT,
	ID_EXPORT_CUT_IMG_BT,
	ID_EXPORT_VIEWPORT,
	ID_FIND_MAX_BT,
	ID_AUTO_UPDATE_CB,
	ID_EXPORT_VTK,
	ID_EXPORT_CUT_CSV_BT,
	ID_COLORSCALE_PROP,
	ID_COLORSCALE_COLORBT,
};
// IDs > wxID_HIGHEST for temporary uses

#endif /* EVENT_IDS_H_ */
